<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyTitle>FMFC Build Tool</AssemblyTitle>
        <Company>Heroic Spirit Games</Company>
        <Version>2.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    </ItemGroup>

</Project>
