using System.Collections.Generic;
using System.Linq;
using FMFCBuildTool.Services;
using Xunit;

namespace FMFCBuildTool.Tests;

public class BatchScriptWriterTests
{
    [Fact]
    public void A_single_command_script_changes_directory_and_forwards_the_exit_code()
    {
        var script = BatchScriptWriter.ForSingleCommand(
            "Package, preset \"Default\"",
            @"C:\Games\FMFC",
            @"C:\UE\RunUAT.bat",
            "BuildCookRun -project=x -build");

        Assert.Contains(@"cd /d ""C:\Games\FMFC""", script);
        Assert.Contains(@"call ""C:\UE\RunUAT.bat"" BuildCookRun -project=x -build", script);

        // A CI step has to be able to tell whether the build worked.
        Assert.Contains("exit /b %ERRORLEVEL%", script);
    }

    [Fact]
    public void A_per_map_script_invokes_the_editor_once_per_map()
    {
        var script = Maps(new[] { "/Game/Maps/A", "/Game/Maps/B" });

        Assert.Equal(2, Occurrences(script, @"""C:\UE\UnrealEditor-Cmd.exe"""));
        Assert.Contains("-map=/Game/Maps/A", script);
        Assert.Contains("-map=/Game/Maps/B", script);
        Assert.Contains("echo [1/2] /Game/Maps/A", script);
        Assert.Contains("echo [2/2] /Game/Maps/B", script);
    }

    /// <summary>
    /// The point of one process per map is that a single bad map does not cost the rest
    /// of the run, so the script must not abort on the first failure — but it must still
    /// end non-zero, or a CI step goes green on a broken build.
    /// </summary>
    [Fact]
    public void A_per_map_script_carries_on_past_a_failure_and_still_exits_non_zero()
    {
        var script = Maps(new[] { "/Game/Maps/A", "/Game/Maps/B" });

        Assert.Equal(2, Occurrences(script, "if errorlevel 1 ("));
        Assert.DoesNotContain("goto :eof", script);

        Assert.Contains("if %FMFC_FAILED%==1 (", script);
        Assert.Contains("exit /b 1", script);
        Assert.Contains("exit /b 0", script);
    }

    [Fact]
    public void Both_forms_are_marked_as_generated()
    {
        Assert.Contains("REM Generated by FMFC Build Tool", Maps(new[] { "/Game/Maps/A" }));

        Assert.Contains(
            "REM Generated by FMFC Build Tool",
            BatchScriptWriter.ForSingleCommand("x", @"C:\p", @"C:\e.bat", "args"));
    }

    private static string Maps(IReadOnlyList<string> maps)
        => BatchScriptWriter.ForEachMap(
            "Navigation build, preset \"Default\"",
            @"C:\Games\FMFC",
            @"C:\UE\UnrealEditor-Cmd.exe",
            maps,
            map => new[] { @"C:\Games\FMFC\FMFC.uproject", "-run=WorldPartitionBuilderCommandlet", $"-map={map}" });

    private static int Occurrences(string text, string needle)
    {
        var count = 0;
        var index = 0;

        while ((index = text.IndexOf(needle, index, System.StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += needle.Length;
        }

        return count;
    }
}
