using System;
using System.Collections.Generic;
using System.Text;

namespace FMFCBuildTool.Services;

/// <summary>
/// Renders a run as a .bat file, so the exact build the UI would launch can also be run
/// from CI, a scheduled task, or another machine without the tool installed.
/// </summary>
/// <remarks>
/// Package could already do this; Navigation and Lighting could not, which is precisely
/// where it is most wanted — a nightly navmesh rebuild is a scheduled job, not something
/// anyone wants to click. The commandlet form is the interesting one: it keeps the
/// per-map loop the UI uses, so one failing map does not abandon the rest, and it exits
/// non-zero if any map failed so a CI step actually goes red.
/// </remarks>
public static class BatchScriptWriter
{
    /// <summary>A single command, as used by Package's RunUAT invocation.</summary>
    public static string ForSingleCommand(string header, string workingDirectory, string exe, string arguments)
    {
        var script = new StringBuilder();

        WritePreamble(script, header, workingDirectory);

        script.AppendLine($"call \"{exe}\" {arguments}");
        script.AppendLine("exit /b %ERRORLEVEL%");

        return script.ToString();
    }

    /// <summary>One invocation per map, mirroring the commandlet pages' run loop.</summary>
    public static string ForEachMap(
        string header,
        string workingDirectory,
        string exe,
        IReadOnlyList<string> maps,
        Func<string, IReadOnlyList<string>> argumentsFor)
    {
        var script = new StringBuilder();

        WritePreamble(script, header, workingDirectory);

        script.AppendLine("set FMFC_FAILED=0");
        script.AppendLine();

        for (var i = 0; i < maps.Count; i++)
        {
            var map = maps[i];

            script.AppendLine($"echo [{i + 1}/{maps.Count}] {map}");
            script.AppendLine($"\"{exe}\" {string.Join(" ", argumentsFor(map))}");

            // Deliberately does not abort: the point of one process per map is that a
            // single bad map does not cost you the whole run.
            script.AppendLine("if errorlevel 1 (");
            script.AppendLine($"    echo FAILED: {map}");
            script.AppendLine("    set FMFC_FAILED=1");
            script.AppendLine(")");
            script.AppendLine();
        }

        script.AppendLine("if %FMFC_FAILED%==1 (");
        script.AppendLine("    echo One or more maps failed.");
        script.AppendLine("    exit /b 1");
        script.AppendLine(")");
        script.AppendLine();
        script.AppendLine("echo All maps succeeded.");
        script.AppendLine("exit /b 0");

        return script.ToString();
    }

    private static void WritePreamble(StringBuilder script, string header, string workingDirectory)
    {
        script.AppendLine("@echo off");
        script.AppendLine($"REM Generated by FMFC Build Tool on {DateTime.Now:yyyy-MM-dd HH:mm} — {header}");
        script.AppendLine($"cd /d \"{workingDirectory}\"");
        script.AppendLine();
    }
}
