using System;
using System.Collections.Generic;
using System.Text;
using FMFCBuildTool.Models;

namespace FMFCBuildTool.Services;

/// <summary>
/// Renders a run as a .bat file, so the exact build the UI would launch can also be run
/// from CI, a scheduled task, or another machine without the tool installed.
/// </summary>
/// <remarks>
/// Package could already do this; Navigation and Lighting could not, which is precisely
/// where it is most wanted — a nightly navmesh rebuild is a scheduled job, not something
/// anyone wants to click. The commandlet form is the interesting one: it keeps the
/// per-map loop the UI uses, so one failing map does not abandon the rest, and it exits
/// non-zero if any map failed so a CI step actually goes red.
/// </remarks>
public static class BatchScriptWriter
{
    /// <summary>A single command, as used by Package's RunUAT invocation.</summary>
    public static string ForSingleCommand(string header, string workingDirectory, string exe, string arguments)
    {
        var script = new StringBuilder();

        WritePreamble(script, header, workingDirectory);

        script.AppendLine($"call \"{exe}\" {arguments}");
        script.AppendLine("exit /b %ERRORLEVEL%");

        return script.ToString();
    }

    /// <summary>One invocation per map, mirroring the commandlet pages' run loop.</summary>
    public static string ForEachMap(
        string header,
        string workingDirectory,
        string exe,
        IReadOnlyList<string> maps,
        Func<string, IReadOnlyList<string>> argumentsFor)
        => ForEachMap(
            header,
            workingDirectory,
            exe,
            maps,
            map => new[] { new CommandletPass("", argumentsFor(map)) });

    /// <summary>
    /// The same loop where a map takes more than one invocation, as HLOD does.
    /// </summary>
    /// <remarks>
    /// Within a map the passes are sequential and abort on the first failure, matching
    /// the UI: building HLODs whose delete pass just failed produces a level nobody
    /// asked for. Between maps nothing aborts, so one bad map still does not cost the run.
    /// </remarks>
    public static string ForEachMap(
        string header,
        string workingDirectory,
        string exe,
        IReadOnlyList<string> maps,
        Func<string, IReadOnlyList<CommandletPass>> passesFor)
    {
        var script = new StringBuilder();

        WritePreamble(script, header, workingDirectory);

        script.AppendLine("set FMFC_FAILED=0");
        script.AppendLine();

        for (var i = 0; i < maps.Count; i++)
        {
            var map = maps[i];
            var passes = passesFor(map);

            script.AppendLine($"echo [{i + 1}/{maps.Count}] {map}");

            // The label only exists to let a reader of the .bat tell the passes apart, so
            // a single-pass map is written exactly as it always was — no label, no jump.
            var done = $":map{i + 1}_done";

            for (var pass = 0; pass < passes.Count; pass++)
            {
                var step = passes[pass].Label.Length > 0 ? $" - {passes[pass].Label}" : "";

                if (step.Length > 0)
                    script.AppendLine($"echo  {step.TrimStart()}");

                script.AppendLine($"\"{exe}\" {string.Join(" ", passes[pass].Arguments)}");

                // Deliberately does not abort the run: the point of one process per map is
                // that a single bad map does not cost you the whole run.
                script.AppendLine("if errorlevel 1 (");
                script.AppendLine($"    echo FAILED: {map}{step}");
                script.AppendLine("    set FMFC_FAILED=1");

                if (pass < passes.Count - 1)
                    script.AppendLine($"    goto {done}");

                script.AppendLine(")");
            }

            if (passes.Count > 1)
                script.AppendLine(done);

            script.AppendLine();
        }

        script.AppendLine("if %FMFC_FAILED%==1 (");
        script.AppendLine("    echo One or more maps failed.");
        script.AppendLine("    exit /b 1");
        script.AppendLine(")");
        script.AppendLine();
        script.AppendLine("echo All maps succeeded.");
        script.AppendLine("exit /b 0");

        return script.ToString();
    }

    private static void WritePreamble(StringBuilder script, string header, string workingDirectory)
    {
        script.AppendLine("@echo off");
        script.AppendLine($"REM Generated by FMFC Build Tool on {DateTime.Now:yyyy-MM-dd HH:mm} — {header}");
        script.AppendLine($"cd /d \"{workingDirectory}\"");
        script.AppendLine();
    }
}
